config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources  :streams do
    resources :comments
    resources :stream_tags, only:[:new, :create]
  end

  resources :tags, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :stream

  validates :user, presence: :true

end

app/models/stream.rb
class Stream < ApplicationRecord
  belongs_to :user
  has_many :stream_tags
  has_many :tags, through: :stream_tags
  has_many :comments, dependent: :destroy
  # has_many :users, through: :comments

  validates :name, presence: :true
  validates :user, presence: :true


end

app/models/stream_tag.rb
class StreamTag < ApplicationRecord
  belongs_to :tag
  belongs_to :stream

end

app/models/tag.rb
class Tag < ApplicationRecord
has_many :stream_tags
has_many :streams, through: :stream_tags

validates :name, presence: :true, uniqueness: :true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

validates :name, presence: :true

has_many :comments
has_many :streams
validates :description, presence: :true, if: :owner?

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_out_path_for(resource_or_scope)
    '/users/sign_up/'
  end

   def after_sign_in_path_for(resource_or_scope)
    streams_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :owner])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_stream

  def index
  end

  #create
  def new
    @comment = Comment.new
  end

  #edit? Or nah?
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.stream = @stream
    @comment.save
    redirect_to stream_path(@stream)
  end

   def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
      redirect_to stream_path(@stream)
  end


  private

  def set_stream
    @stream = Stream.find(params[:stream_id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def comment_params
    params.require(:comment).permit(:content, :stream_id, :user_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authenticate_user!
  def home
  end
end

app/controllers/stream_tags_controller.rb
class StreamTagsController < ApplicationController

  def new
    @stream = Stream.find(params[:stream_id])
    @tags = Tag.all
  end

  def create

    @stream = Stream.find(params[:stream_id])
    @stream_tag = StreamTag.new(stream_tag_params)
    @stream_tag.stream = @stream
    @stream_tag.save
    redirect_to stream_path(@stream)

  end

  private

  def stream_tag_params
    params.require(:stream_tag).permit(:tag_id)
  end

end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  before_action :set_stream, only: [:show, :update, :destroy]

  def index
    @streams = Stream.all
  end

  def show
      @new_comment = Comment.new
      @stream_tag = StreamTag.new
      @tags = Tag.all
  end

  def new
    #if :owner?
      @stream = Stream.new
    #else
     # redirect_to streams_path
    #end

    # check if the owner_id boolean == true
    # if not, reject method
  end

  def edit
    # if current_user.owner?
      @stream = Stream.find(params[:id])
    # else
    #  redirect_to streams_path
    # end
    # check if the owner_id boolean == true
    # if not, reject method
  end

  def create
    # if current_user.owner?
      @stream = Stream.new(stream_params)#owner_id part of the augment too?
      @stream.user = current_user
      if @stream.save
        redirect_to stream_path(@stream)
      else
        render :new
      end
    # else
      # redirect_to streams_path
    # end
  end

  def update
    @stream.update(stream_params)
    redirect_to stream_path
  end

  def destroy
    #if current_user.owner?
      @stream.destroy
      redirect_to streams_path
    # else
    #  redirect_to streams_path
    #end
    # check if the owner_id boolean == true
    # if not, reject method
  end


  private

  def set_stream
    @stream = Stream.find(params[:id])
  end

  def stream_params
    params.require(:stream).permit(:name, :link, :description, :comments)
    # this prevents users from inserting new db columns into the db
    # so we define what columns DO exist/are approved
  end

end

app/controllers/tag_streams_controller.rb
class TagStreamsController < ApplicationController
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

def index
  @tags = Tag.all
end

def show
  @tag = Tag.find(params[:id])

  @streams = @tag.streams
end

end

app/controllers/user_streams_controller.rb
class UserStreamsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/owner_streams_helper.rb
module OwnerStreamsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/helpers/tag_streams_helper.rb
module TagStreamsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/streams/_tag.html.erb
<h1>tags</h1>

<p>Tag Name: <%= tag.name %> </p>



  from the index file <%= render partial: "tags", collection: @tags %>

app/views/streams/edit.html.erb
<h1>Stream Edit</h1>
<p>Should be able to edit the Stream Here</p>

<% @streams = Stream.find(params[:id])%>

<%= form_for(@streams) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :link %>
  <%= f.text_field :link %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/streams/index.html.erb
<h1>Streams Index</h1>
<p>This should list all the streams in the db</p>

<% @streams.each do |stream| %>

  <h3><%= stream.name%></h3>

  <p>Category</p>

<% stream.tags.uniq.each do |tag| %>
  <%= tag.name %>

<% end %>

</p>

  <%= stream.link%>
  <p>

  <%= link_to 'Show', stream %>
  </p>
<% end %>

<%= link_to 'Create a new Stream', new_stream_path %>

app/views/streams/new.html.erb
<h1>New Stream</h1>
<p>Owners can make a new Stream Here</p>

<%= form_for(@stream) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :link %>
  <%= f.text_field :link %>

  <%= f.label :description %>
  <%= f.text_field :description %>


  <%= f.submit %>
<% end %>

app/views/streams/show.html.erb
<% @streams = Stream.find(params[:id])%>

<h1><%= @streams.name %></h1>
<p><%= @streams.link %></p>
<p><%= @streams.description %></p>
<p><% @stream.tags.uniq.each do |tag| %>
  <%= tag.name %>
</p>

<% end %>

<p>

<p> Add tag to stream </p>
<%= form_for ([@stream, @stream_tag]) do |f| %>
  <%= f.label 'Create Tag' %>
  <%= f.collection_select(:tag_id, @tags, :id, :name) %>
  <%= f.submit %>
<% end %>


     <%= link_to 'Edit Stream', edit_stream_url %>
     <br>
      <%= link_to 'Destroy Stream', @stream , method: :delete, data: { confirm: 'Delete Stream?'} %>
     <br>

</p>


<strong>Comments</strong>
<br>
  <% @stream.comments.each do |comment| %>
    <%= comment.user.name %>
    <%= comment.content %>
    <%= link_to 'Delete', [@stream, comment] , method: :delete, data: { confirm: 'Delete Comment?'} %>
<br>
<% end %>

<br>
<%= form_for ([@stream, @new_comment]) do |f| %>
  <%= f.label 'Create Comment' %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

<p><%= link_to 'Go Back to Index', streams_path %></p>

app/views/tags/show.html.erb
<% @tag.streams.each do |stream| %>

<h3> <%= stream.name %> </h3>

<% end  %>

app/views/tags/view.html.erb
<% @tag = Tag.find(params[:id]) %>

<<h1>Streams per tag </h1>

<<p> Here a nice list of streams per tag </p>

<% @tag.streams each do | stream | %>

<h3><%= stream.name %></h3>
<%= stream.link %>
<p>
  <%= link_to 'show', stream %>
</p>
<% end  %>

<%= link_to 'Home', root_path %>